# Generated by Django 4.1.7 on 2023-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
