# Generated by Django 4.1.7 on 2023-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngblog', '0002_alter_post_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
