# Generated by Django 4.1.7 on 2023-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngblog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image'),
        ),
    ]
