# Generated by Django 4.1.7 on 2023-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngblog', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
