# Generated by Django 4.1.7 on 2023-04-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngblog', '0018_post_author_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
